[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
